# Generated by Django 3.2.6 on 2021-08-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uploadedFile',
            field=models.FileField(default='', upload_to='Uploaded Files/'),
        ),
    ]
