# Generated by Django 3.2.6 on 2021-08-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_uploadedfile_ticket_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='uploaded_file',
            field=models.FileField(default='', upload_to='User-Story-Files/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uploaded_file',
            field=models.FileField(default='', upload_to='Task-Files/'),
        ),
    ]
